#!/bin/sh
#$ -S /bin/sh
#$ -cwd 
#$ -l s_vmem=1G,mem_req=1G
#$ -l short
#$ -pe def_slot 1
#$ -o ./log
#$ -e ./log

source ~/.bashrc
cd /home/takeshik/tanomare/dstep20180126

arr=( ERR003990_1.trimmomatic.fq ERR003990_2.trimmomatic.fq ERR003991_1.fastq ERR003991_2.fastq ERR003992_1.fastq ERR003992_2.fastq )

i=$(( $SGE_TASK_ID -1 ))
j=$(( $i * 2 ))
k=$(( $j + 1 ))

bowtie2 -q -x Danio_rerio.GRCz10.dna.chromosome.9.fa -1 ${arr[$j]} -2 ${arr[$k]} -S danio.${arr[$j]}.pe.sam

